### ISSUE TITLE
Invalid syntax: "for a range"

### ISSUE THREAD

**Issue by InfoTeddy** [Flipnote-Collective/kwz-parser#6]
Looks like the latest commit 5196b6fca55cf838f66777271ec8edcea993eed6 removed the `in`s from a bunch of `for a in range` constructs, thus ending up as invalid syntax.

This means that no one has ever tested or even used this code in a few months, since that syntax error would have been resolved already if so. Until today, where someone linked this code in a Discord server I'm in because they were trying to use it.

**Comment by jaames** [comment]
Oops, sorry about that! That change was indeed added in a rush without testing it.

I just pushed a fix (and tested it properly this time :P). Thanks for the heads-up.
